// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/order"
	"github.com/Wei-Shaw/sub2api/ent/plan"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// OrderUpdate is the builder for updating Order entities.
type OrderUpdate struct {
	config
	hooks    []Hook
	mutation *OrderMutation
}

// Where appends a list predicates to the OrderUpdate builder.
func (_u *OrderUpdate) Where(ps ...predicate.Order) *OrderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OrderUpdate) SetUpdatedAt(v time.Time) *OrderUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *OrderUpdate) SetDeletedAt(v time.Time) *OrderUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableDeletedAt(v *time.Time) *OrderUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *OrderUpdate) ClearDeletedAt() *OrderUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *OrderUpdate) SetUserID(v int64) *OrderUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableUserID(v *int64) *OrderUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetPlanID sets the "plan_id" field.
func (_u *OrderUpdate) SetPlanID(v int64) *OrderUpdate {
	_u.mutation.SetPlanID(v)
	return _u
}

// SetNillablePlanID sets the "plan_id" field if the given value is not nil.
func (_u *OrderUpdate) SetNillablePlanID(v *int64) *OrderUpdate {
	if v != nil {
		_u.SetPlanID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *OrderUpdate) SetStatus(v string) *OrderUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableStatus(v *string) *OrderUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *OrderUpdate) SetAmount(v int) *OrderUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableAmount(v *int) *OrderUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *OrderUpdate) AddAmount(v int) *OrderUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetNotes sets the "notes" field.
func (_u *OrderUpdate) SetNotes(v string) *OrderUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableNotes(v *string) *OrderUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *OrderUpdate) ClearNotes() *OrderUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// SetConfirmedBy sets the "confirmed_by" field.
func (_u *OrderUpdate) SetConfirmedBy(v int64) *OrderUpdate {
	_u.mutation.SetConfirmedBy(v)
	return _u
}

// SetNillableConfirmedBy sets the "confirmed_by" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableConfirmedBy(v *int64) *OrderUpdate {
	if v != nil {
		_u.SetConfirmedBy(*v)
	}
	return _u
}

// ClearConfirmedBy clears the value of the "confirmed_by" field.
func (_u *OrderUpdate) ClearConfirmedBy() *OrderUpdate {
	_u.mutation.ClearConfirmedBy()
	return _u
}

// SetConfirmedAt sets the "confirmed_at" field.
func (_u *OrderUpdate) SetConfirmedAt(v time.Time) *OrderUpdate {
	_u.mutation.SetConfirmedAt(v)
	return _u
}

// SetNillableConfirmedAt sets the "confirmed_at" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableConfirmedAt(v *time.Time) *OrderUpdate {
	if v != nil {
		_u.SetConfirmedAt(*v)
	}
	return _u
}

// ClearConfirmedAt clears the value of the "confirmed_at" field.
func (_u *OrderUpdate) ClearConfirmedAt() *OrderUpdate {
	_u.mutation.ClearConfirmedAt()
	return _u
}

// SetOrderedAt sets the "ordered_at" field.
func (_u *OrderUpdate) SetOrderedAt(v time.Time) *OrderUpdate {
	_u.mutation.SetOrderedAt(v)
	return _u
}

// SetNillableOrderedAt sets the "ordered_at" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableOrderedAt(v *time.Time) *OrderUpdate {
	if v != nil {
		_u.SetOrderedAt(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *OrderUpdate) SetUser(v *User) *OrderUpdate {
	return _u.SetUserID(v.ID)
}

// SetPlan sets the "plan" edge to the Plan entity.
func (_u *OrderUpdate) SetPlan(v *Plan) *OrderUpdate {
	return _u.SetPlanID(v.ID)
}

// SetConfirmedByUserID sets the "confirmed_by_user" edge to the User entity by ID.
func (_u *OrderUpdate) SetConfirmedByUserID(id int64) *OrderUpdate {
	_u.mutation.SetConfirmedByUserID(id)
	return _u
}

// SetNillableConfirmedByUserID sets the "confirmed_by_user" edge to the User entity by ID if the given value is not nil.
func (_u *OrderUpdate) SetNillableConfirmedByUserID(id *int64) *OrderUpdate {
	if id != nil {
		_u = _u.SetConfirmedByUserID(*id)
	}
	return _u
}

// SetConfirmedByUser sets the "confirmed_by_user" edge to the User entity.
func (_u *OrderUpdate) SetConfirmedByUser(v *User) *OrderUpdate {
	return _u.SetConfirmedByUserID(v.ID)
}

// Mutation returns the OrderMutation object of the builder.
func (_u *OrderUpdate) Mutation() *OrderMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *OrderUpdate) ClearUser() *OrderUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearPlan clears the "plan" edge to the Plan entity.
func (_u *OrderUpdate) ClearPlan() *OrderUpdate {
	_u.mutation.ClearPlan()
	return _u
}

// ClearConfirmedByUser clears the "confirmed_by_user" edge to the User entity.
func (_u *OrderUpdate) ClearConfirmedByUser() *OrderUpdate {
	_u.mutation.ClearConfirmedByUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OrderUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OrderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OrderUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if order.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized order.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := order.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *OrderUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := order.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Order.status": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Order.user"`)
	}
	if _u.mutation.PlanCleared() && len(_u.mutation.PlanIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Order.plan"`)
	}
	return nil
}

func (_u *OrderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(order.Table, order.Columns, sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(order.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(order.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(order.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(order.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(order.FieldAmount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(order.FieldAmount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(order.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(order.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.ConfirmedAt(); ok {
		_spec.SetField(order.FieldConfirmedAt, field.TypeTime, value)
	}
	if _u.mutation.ConfirmedAtCleared() {
		_spec.ClearField(order.FieldConfirmedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.OrderedAt(); ok {
		_spec.SetField(order.FieldOrderedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.UserTable,
			Columns: []string{order.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.UserTable,
			Columns: []string{order.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PlanCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.PlanTable,
			Columns: []string{order.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.PlanTable,
			Columns: []string{order.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ConfirmedByUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.ConfirmedByUserTable,
			Columns: []string{order.ConfirmedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConfirmedByUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.ConfirmedByUserTable,
			Columns: []string{order.ConfirmedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{order.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OrderUpdateOne is the builder for updating a single Order entity.
type OrderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OrderMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OrderUpdateOne) SetUpdatedAt(v time.Time) *OrderUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *OrderUpdateOne) SetDeletedAt(v time.Time) *OrderUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableDeletedAt(v *time.Time) *OrderUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *OrderUpdateOne) ClearDeletedAt() *OrderUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *OrderUpdateOne) SetUserID(v int64) *OrderUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableUserID(v *int64) *OrderUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetPlanID sets the "plan_id" field.
func (_u *OrderUpdateOne) SetPlanID(v int64) *OrderUpdateOne {
	_u.mutation.SetPlanID(v)
	return _u
}

// SetNillablePlanID sets the "plan_id" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillablePlanID(v *int64) *OrderUpdateOne {
	if v != nil {
		_u.SetPlanID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *OrderUpdateOne) SetStatus(v string) *OrderUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableStatus(v *string) *OrderUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *OrderUpdateOne) SetAmount(v int) *OrderUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableAmount(v *int) *OrderUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *OrderUpdateOne) AddAmount(v int) *OrderUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetNotes sets the "notes" field.
func (_u *OrderUpdateOne) SetNotes(v string) *OrderUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableNotes(v *string) *OrderUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *OrderUpdateOne) ClearNotes() *OrderUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// SetConfirmedBy sets the "confirmed_by" field.
func (_u *OrderUpdateOne) SetConfirmedBy(v int64) *OrderUpdateOne {
	_u.mutation.SetConfirmedBy(v)
	return _u
}

// SetNillableConfirmedBy sets the "confirmed_by" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableConfirmedBy(v *int64) *OrderUpdateOne {
	if v != nil {
		_u.SetConfirmedBy(*v)
	}
	return _u
}

// ClearConfirmedBy clears the value of the "confirmed_by" field.
func (_u *OrderUpdateOne) ClearConfirmedBy() *OrderUpdateOne {
	_u.mutation.ClearConfirmedBy()
	return _u
}

// SetConfirmedAt sets the "confirmed_at" field.
func (_u *OrderUpdateOne) SetConfirmedAt(v time.Time) *OrderUpdateOne {
	_u.mutation.SetConfirmedAt(v)
	return _u
}

// SetNillableConfirmedAt sets the "confirmed_at" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableConfirmedAt(v *time.Time) *OrderUpdateOne {
	if v != nil {
		_u.SetConfirmedAt(*v)
	}
	return _u
}

// ClearConfirmedAt clears the value of the "confirmed_at" field.
func (_u *OrderUpdateOne) ClearConfirmedAt() *OrderUpdateOne {
	_u.mutation.ClearConfirmedAt()
	return _u
}

// SetOrderedAt sets the "ordered_at" field.
func (_u *OrderUpdateOne) SetOrderedAt(v time.Time) *OrderUpdateOne {
	_u.mutation.SetOrderedAt(v)
	return _u
}

// SetNillableOrderedAt sets the "ordered_at" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableOrderedAt(v *time.Time) *OrderUpdateOne {
	if v != nil {
		_u.SetOrderedAt(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *OrderUpdateOne) SetUser(v *User) *OrderUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetPlan sets the "plan" edge to the Plan entity.
func (_u *OrderUpdateOne) SetPlan(v *Plan) *OrderUpdateOne {
	return _u.SetPlanID(v.ID)
}

// SetConfirmedByUserID sets the "confirmed_by_user" edge to the User entity by ID.
func (_u *OrderUpdateOne) SetConfirmedByUserID(id int64) *OrderUpdateOne {
	_u.mutation.SetConfirmedByUserID(id)
	return _u
}

// SetNillableConfirmedByUserID sets the "confirmed_by_user" edge to the User entity by ID if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableConfirmedByUserID(id *int64) *OrderUpdateOne {
	if id != nil {
		_u = _u.SetConfirmedByUserID(*id)
	}
	return _u
}

// SetConfirmedByUser sets the "confirmed_by_user" edge to the User entity.
func (_u *OrderUpdateOne) SetConfirmedByUser(v *User) *OrderUpdateOne {
	return _u.SetConfirmedByUserID(v.ID)
}

// Mutation returns the OrderMutation object of the builder.
func (_u *OrderUpdateOne) Mutation() *OrderMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *OrderUpdateOne) ClearUser() *OrderUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearPlan clears the "plan" edge to the Plan entity.
func (_u *OrderUpdateOne) ClearPlan() *OrderUpdateOne {
	_u.mutation.ClearPlan()
	return _u
}

// ClearConfirmedByUser clears the "confirmed_by_user" edge to the User entity.
func (_u *OrderUpdateOne) ClearConfirmedByUser() *OrderUpdateOne {
	_u.mutation.ClearConfirmedByUser()
	return _u
}

// Where appends a list predicates to the OrderUpdate builder.
func (_u *OrderUpdateOne) Where(ps ...predicate.Order) *OrderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OrderUpdateOne) Select(field string, fields ...string) *OrderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Order entity.
func (_u *OrderUpdateOne) Save(ctx context.Context) (*Order, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrderUpdateOne) SaveX(ctx context.Context) *Order {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OrderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OrderUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if order.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized order.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := order.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *OrderUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := order.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Order.status": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Order.user"`)
	}
	if _u.mutation.PlanCleared() && len(_u.mutation.PlanIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Order.plan"`)
	}
	return nil
}

func (_u *OrderUpdateOne) sqlSave(ctx context.Context) (_node *Order, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(order.Table, order.Columns, sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Order.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, order.FieldID)
		for _, f := range fields {
			if !order.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != order.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(order.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(order.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(order.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(order.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(order.FieldAmount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(order.FieldAmount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(order.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(order.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.ConfirmedAt(); ok {
		_spec.SetField(order.FieldConfirmedAt, field.TypeTime, value)
	}
	if _u.mutation.ConfirmedAtCleared() {
		_spec.ClearField(order.FieldConfirmedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.OrderedAt(); ok {
		_spec.SetField(order.FieldOrderedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.UserTable,
			Columns: []string{order.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.UserTable,
			Columns: []string{order.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PlanCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.PlanTable,
			Columns: []string{order.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.PlanTable,
			Columns: []string{order.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ConfirmedByUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.ConfirmedByUserTable,
			Columns: []string{order.ConfirmedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConfirmedByUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.ConfirmedByUserTable,
			Columns: []string{order.ConfirmedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Order{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{order.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
