// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/order"
	"github.com/Wei-Shaw/sub2api/ent/plan"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// OrderCreate is the builder for creating a Order entity.
type OrderCreate struct {
	config
	mutation *OrderMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *OrderCreate) SetCreatedAt(v time.Time) *OrderCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OrderCreate) SetNillableCreatedAt(v *time.Time) *OrderCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OrderCreate) SetUpdatedAt(v time.Time) *OrderCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OrderCreate) SetNillableUpdatedAt(v *time.Time) *OrderCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *OrderCreate) SetDeletedAt(v time.Time) *OrderCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *OrderCreate) SetNillableDeletedAt(v *time.Time) *OrderCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *OrderCreate) SetUserID(v int64) *OrderCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetPlanID sets the "plan_id" field.
func (_c *OrderCreate) SetPlanID(v int64) *OrderCreate {
	_c.mutation.SetPlanID(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *OrderCreate) SetStatus(v string) *OrderCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *OrderCreate) SetNillableStatus(v *string) *OrderCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetAmount sets the "amount" field.
func (_c *OrderCreate) SetAmount(v int) *OrderCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_c *OrderCreate) SetNillableAmount(v *int) *OrderCreate {
	if v != nil {
		_c.SetAmount(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *OrderCreate) SetNotes(v string) *OrderCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *OrderCreate) SetNillableNotes(v *string) *OrderCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetConfirmedBy sets the "confirmed_by" field.
func (_c *OrderCreate) SetConfirmedBy(v int64) *OrderCreate {
	_c.mutation.SetConfirmedBy(v)
	return _c
}

// SetNillableConfirmedBy sets the "confirmed_by" field if the given value is not nil.
func (_c *OrderCreate) SetNillableConfirmedBy(v *int64) *OrderCreate {
	if v != nil {
		_c.SetConfirmedBy(*v)
	}
	return _c
}

// SetConfirmedAt sets the "confirmed_at" field.
func (_c *OrderCreate) SetConfirmedAt(v time.Time) *OrderCreate {
	_c.mutation.SetConfirmedAt(v)
	return _c
}

// SetNillableConfirmedAt sets the "confirmed_at" field if the given value is not nil.
func (_c *OrderCreate) SetNillableConfirmedAt(v *time.Time) *OrderCreate {
	if v != nil {
		_c.SetConfirmedAt(*v)
	}
	return _c
}

// SetOrderedAt sets the "ordered_at" field.
func (_c *OrderCreate) SetOrderedAt(v time.Time) *OrderCreate {
	_c.mutation.SetOrderedAt(v)
	return _c
}

// SetNillableOrderedAt sets the "ordered_at" field if the given value is not nil.
func (_c *OrderCreate) SetNillableOrderedAt(v *time.Time) *OrderCreate {
	if v != nil {
		_c.SetOrderedAt(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *OrderCreate) SetUser(v *User) *OrderCreate {
	return _c.SetUserID(v.ID)
}

// SetPlan sets the "plan" edge to the Plan entity.
func (_c *OrderCreate) SetPlan(v *Plan) *OrderCreate {
	return _c.SetPlanID(v.ID)
}

// SetConfirmedByUserID sets the "confirmed_by_user" edge to the User entity by ID.
func (_c *OrderCreate) SetConfirmedByUserID(id int64) *OrderCreate {
	_c.mutation.SetConfirmedByUserID(id)
	return _c
}

// SetNillableConfirmedByUserID sets the "confirmed_by_user" edge to the User entity by ID if the given value is not nil.
func (_c *OrderCreate) SetNillableConfirmedByUserID(id *int64) *OrderCreate {
	if id != nil {
		_c = _c.SetConfirmedByUserID(*id)
	}
	return _c
}

// SetConfirmedByUser sets the "confirmed_by_user" edge to the User entity.
func (_c *OrderCreate) SetConfirmedByUser(v *User) *OrderCreate {
	return _c.SetConfirmedByUserID(v.ID)
}

// Mutation returns the OrderMutation object of the builder.
func (_c *OrderCreate) Mutation() *OrderMutation {
	return _c.mutation
}

// Save creates the Order in the database.
func (_c *OrderCreate) Save(ctx context.Context) (*Order, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OrderCreate) SaveX(ctx context.Context) *Order {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OrderCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OrderCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OrderCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if order.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized order.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := order.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if order.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized order.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := order.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := order.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Amount(); !ok {
		v := order.DefaultAmount
		_c.mutation.SetAmount(v)
	}
	if _, ok := _c.mutation.OrderedAt(); !ok {
		if order.DefaultOrderedAt == nil {
			return fmt.Errorf("ent: uninitialized order.DefaultOrderedAt (forgotten import ent/runtime?)")
		}
		v := order.DefaultOrderedAt()
		_c.mutation.SetOrderedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *OrderCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Order.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Order.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Order.user_id"`)}
	}
	if _, ok := _c.mutation.PlanID(); !ok {
		return &ValidationError{Name: "plan_id", err: errors.New(`ent: missing required field "Order.plan_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Order.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := order.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Order.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "Order.amount"`)}
	}
	if _, ok := _c.mutation.OrderedAt(); !ok {
		return &ValidationError{Name: "ordered_at", err: errors.New(`ent: missing required field "Order.ordered_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Order.user"`)}
	}
	if len(_c.mutation.PlanIDs()) == 0 {
		return &ValidationError{Name: "plan", err: errors.New(`ent: missing required edge "Order.plan"`)}
	}
	return nil
}

func (_c *OrderCreate) sqlSave(ctx context.Context) (*Order, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OrderCreate) createSpec() (*Order, *sqlgraph.CreateSpec) {
	var (
		_node = &Order{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(order.Table, sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(order.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(order.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(order.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(order.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(order.FieldAmount, field.TypeInt, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(order.FieldNotes, field.TypeString, value)
		_node.Notes = &value
	}
	if value, ok := _c.mutation.ConfirmedAt(); ok {
		_spec.SetField(order.FieldConfirmedAt, field.TypeTime, value)
		_node.ConfirmedAt = &value
	}
	if value, ok := _c.mutation.OrderedAt(); ok {
		_spec.SetField(order.FieldOrderedAt, field.TypeTime, value)
		_node.OrderedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.UserTable,
			Columns: []string{order.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.PlanTable,
			Columns: []string{order.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PlanID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ConfirmedByUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.ConfirmedByUserTable,
			Columns: []string{order.ConfirmedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ConfirmedBy = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Order.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OrderUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OrderCreate) OnConflict(opts ...sql.ConflictOption) *OrderUpsertOne {
	_c.conflict = opts
	return &OrderUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Order.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OrderCreate) OnConflictColumns(columns ...string) *OrderUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OrderUpsertOne{
		create: _c,
	}
}

type (
	// OrderUpsertOne is the builder for "upsert"-ing
	//  one Order node.
	OrderUpsertOne struct {
		create *OrderCreate
	}

	// OrderUpsert is the "OnConflict" setter.
	OrderUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *OrderUpsert) SetUpdatedAt(v time.Time) *OrderUpsert {
	u.Set(order.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OrderUpsert) UpdateUpdatedAt() *OrderUpsert {
	u.SetExcluded(order.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *OrderUpsert) SetDeletedAt(v time.Time) *OrderUpsert {
	u.Set(order.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *OrderUpsert) UpdateDeletedAt() *OrderUpsert {
	u.SetExcluded(order.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *OrderUpsert) ClearDeletedAt() *OrderUpsert {
	u.SetNull(order.FieldDeletedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *OrderUpsert) SetUserID(v int64) *OrderUpsert {
	u.Set(order.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *OrderUpsert) UpdateUserID() *OrderUpsert {
	u.SetExcluded(order.FieldUserID)
	return u
}

// SetPlanID sets the "plan_id" field.
func (u *OrderUpsert) SetPlanID(v int64) *OrderUpsert {
	u.Set(order.FieldPlanID, v)
	return u
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *OrderUpsert) UpdatePlanID() *OrderUpsert {
	u.SetExcluded(order.FieldPlanID)
	return u
}

// SetStatus sets the "status" field.
func (u *OrderUpsert) SetStatus(v string) *OrderUpsert {
	u.Set(order.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OrderUpsert) UpdateStatus() *OrderUpsert {
	u.SetExcluded(order.FieldStatus)
	return u
}

// SetAmount sets the "amount" field.
func (u *OrderUpsert) SetAmount(v int) *OrderUpsert {
	u.Set(order.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *OrderUpsert) UpdateAmount() *OrderUpsert {
	u.SetExcluded(order.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *OrderUpsert) AddAmount(v int) *OrderUpsert {
	u.Add(order.FieldAmount, v)
	return u
}

// SetNotes sets the "notes" field.
func (u *OrderUpsert) SetNotes(v string) *OrderUpsert {
	u.Set(order.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *OrderUpsert) UpdateNotes() *OrderUpsert {
	u.SetExcluded(order.FieldNotes)
	return u
}

// ClearNotes clears the value of the "notes" field.
func (u *OrderUpsert) ClearNotes() *OrderUpsert {
	u.SetNull(order.FieldNotes)
	return u
}

// SetConfirmedBy sets the "confirmed_by" field.
func (u *OrderUpsert) SetConfirmedBy(v int64) *OrderUpsert {
	u.Set(order.FieldConfirmedBy, v)
	return u
}

// UpdateConfirmedBy sets the "confirmed_by" field to the value that was provided on create.
func (u *OrderUpsert) UpdateConfirmedBy() *OrderUpsert {
	u.SetExcluded(order.FieldConfirmedBy)
	return u
}

// ClearConfirmedBy clears the value of the "confirmed_by" field.
func (u *OrderUpsert) ClearConfirmedBy() *OrderUpsert {
	u.SetNull(order.FieldConfirmedBy)
	return u
}

// SetConfirmedAt sets the "confirmed_at" field.
func (u *OrderUpsert) SetConfirmedAt(v time.Time) *OrderUpsert {
	u.Set(order.FieldConfirmedAt, v)
	return u
}

// UpdateConfirmedAt sets the "confirmed_at" field to the value that was provided on create.
func (u *OrderUpsert) UpdateConfirmedAt() *OrderUpsert {
	u.SetExcluded(order.FieldConfirmedAt)
	return u
}

// ClearConfirmedAt clears the value of the "confirmed_at" field.
func (u *OrderUpsert) ClearConfirmedAt() *OrderUpsert {
	u.SetNull(order.FieldConfirmedAt)
	return u
}

// SetOrderedAt sets the "ordered_at" field.
func (u *OrderUpsert) SetOrderedAt(v time.Time) *OrderUpsert {
	u.Set(order.FieldOrderedAt, v)
	return u
}

// UpdateOrderedAt sets the "ordered_at" field to the value that was provided on create.
func (u *OrderUpsert) UpdateOrderedAt() *OrderUpsert {
	u.SetExcluded(order.FieldOrderedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Order.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OrderUpsertOne) UpdateNewValues() *OrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(order.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Order.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OrderUpsertOne) Ignore() *OrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OrderUpsertOne) DoNothing() *OrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OrderCreate.OnConflict
// documentation for more info.
func (u *OrderUpsertOne) Update(set func(*OrderUpsert)) *OrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OrderUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OrderUpsertOne) SetUpdatedAt(v time.Time) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OrderUpsertOne) UpdateUpdatedAt() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *OrderUpsertOne) SetDeletedAt(v time.Time) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *OrderUpsertOne) UpdateDeletedAt() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *OrderUpsertOne) ClearDeletedAt() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *OrderUpsertOne) SetUserID(v int64) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *OrderUpsertOne) UpdateUserID() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateUserID()
	})
}

// SetPlanID sets the "plan_id" field.
func (u *OrderUpsertOne) SetPlanID(v int64) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.SetPlanID(v)
	})
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *OrderUpsertOne) UpdatePlanID() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.UpdatePlanID()
	})
}

// SetStatus sets the "status" field.
func (u *OrderUpsertOne) SetStatus(v string) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OrderUpsertOne) UpdateStatus() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateStatus()
	})
}

// SetAmount sets the "amount" field.
func (u *OrderUpsertOne) SetAmount(v int) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *OrderUpsertOne) AddAmount(v int) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *OrderUpsertOne) UpdateAmount() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateAmount()
	})
}

// SetNotes sets the "notes" field.
func (u *OrderUpsertOne) SetNotes(v string) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *OrderUpsertOne) UpdateNotes() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *OrderUpsertOne) ClearNotes() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.ClearNotes()
	})
}

// SetConfirmedBy sets the "confirmed_by" field.
func (u *OrderUpsertOne) SetConfirmedBy(v int64) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.SetConfirmedBy(v)
	})
}

// UpdateConfirmedBy sets the "confirmed_by" field to the value that was provided on create.
func (u *OrderUpsertOne) UpdateConfirmedBy() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateConfirmedBy()
	})
}

// ClearConfirmedBy clears the value of the "confirmed_by" field.
func (u *OrderUpsertOne) ClearConfirmedBy() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.ClearConfirmedBy()
	})
}

// SetConfirmedAt sets the "confirmed_at" field.
func (u *OrderUpsertOne) SetConfirmedAt(v time.Time) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.SetConfirmedAt(v)
	})
}

// UpdateConfirmedAt sets the "confirmed_at" field to the value that was provided on create.
func (u *OrderUpsertOne) UpdateConfirmedAt() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateConfirmedAt()
	})
}

// ClearConfirmedAt clears the value of the "confirmed_at" field.
func (u *OrderUpsertOne) ClearConfirmedAt() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.ClearConfirmedAt()
	})
}

// SetOrderedAt sets the "ordered_at" field.
func (u *OrderUpsertOne) SetOrderedAt(v time.Time) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.SetOrderedAt(v)
	})
}

// UpdateOrderedAt sets the "ordered_at" field to the value that was provided on create.
func (u *OrderUpsertOne) UpdateOrderedAt() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateOrderedAt()
	})
}

// Exec executes the query.
func (u *OrderUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OrderCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OrderUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OrderUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OrderUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OrderCreateBulk is the builder for creating many Order entities in bulk.
type OrderCreateBulk struct {
	config
	err      error
	builders []*OrderCreate
	conflict []sql.ConflictOption
}

// Save creates the Order entities in the database.
func (_c *OrderCreateBulk) Save(ctx context.Context) ([]*Order, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Order, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OrderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OrderCreateBulk) SaveX(ctx context.Context) []*Order {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OrderCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OrderCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Order.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OrderUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OrderCreateBulk) OnConflict(opts ...sql.ConflictOption) *OrderUpsertBulk {
	_c.conflict = opts
	return &OrderUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Order.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OrderCreateBulk) OnConflictColumns(columns ...string) *OrderUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OrderUpsertBulk{
		create: _c,
	}
}

// OrderUpsertBulk is the builder for "upsert"-ing
// a bulk of Order nodes.
type OrderUpsertBulk struct {
	create *OrderCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Order.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OrderUpsertBulk) UpdateNewValues() *OrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(order.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Order.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OrderUpsertBulk) Ignore() *OrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OrderUpsertBulk) DoNothing() *OrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OrderCreateBulk.OnConflict
// documentation for more info.
func (u *OrderUpsertBulk) Update(set func(*OrderUpsert)) *OrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OrderUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OrderUpsertBulk) SetUpdatedAt(v time.Time) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OrderUpsertBulk) UpdateUpdatedAt() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *OrderUpsertBulk) SetDeletedAt(v time.Time) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *OrderUpsertBulk) UpdateDeletedAt() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *OrderUpsertBulk) ClearDeletedAt() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *OrderUpsertBulk) SetUserID(v int64) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *OrderUpsertBulk) UpdateUserID() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateUserID()
	})
}

// SetPlanID sets the "plan_id" field.
func (u *OrderUpsertBulk) SetPlanID(v int64) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.SetPlanID(v)
	})
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *OrderUpsertBulk) UpdatePlanID() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.UpdatePlanID()
	})
}

// SetStatus sets the "status" field.
func (u *OrderUpsertBulk) SetStatus(v string) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OrderUpsertBulk) UpdateStatus() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateStatus()
	})
}

// SetAmount sets the "amount" field.
func (u *OrderUpsertBulk) SetAmount(v int) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *OrderUpsertBulk) AddAmount(v int) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *OrderUpsertBulk) UpdateAmount() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateAmount()
	})
}

// SetNotes sets the "notes" field.
func (u *OrderUpsertBulk) SetNotes(v string) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *OrderUpsertBulk) UpdateNotes() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *OrderUpsertBulk) ClearNotes() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.ClearNotes()
	})
}

// SetConfirmedBy sets the "confirmed_by" field.
func (u *OrderUpsertBulk) SetConfirmedBy(v int64) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.SetConfirmedBy(v)
	})
}

// UpdateConfirmedBy sets the "confirmed_by" field to the value that was provided on create.
func (u *OrderUpsertBulk) UpdateConfirmedBy() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateConfirmedBy()
	})
}

// ClearConfirmedBy clears the value of the "confirmed_by" field.
func (u *OrderUpsertBulk) ClearConfirmedBy() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.ClearConfirmedBy()
	})
}

// SetConfirmedAt sets the "confirmed_at" field.
func (u *OrderUpsertBulk) SetConfirmedAt(v time.Time) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.SetConfirmedAt(v)
	})
}

// UpdateConfirmedAt sets the "confirmed_at" field to the value that was provided on create.
func (u *OrderUpsertBulk) UpdateConfirmedAt() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateConfirmedAt()
	})
}

// ClearConfirmedAt clears the value of the "confirmed_at" field.
func (u *OrderUpsertBulk) ClearConfirmedAt() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.ClearConfirmedAt()
	})
}

// SetOrderedAt sets the "ordered_at" field.
func (u *OrderUpsertBulk) SetOrderedAt(v time.Time) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.SetOrderedAt(v)
	})
}

// UpdateOrderedAt sets the "ordered_at" field to the value that was provided on create.
func (u *OrderUpsertBulk) UpdateOrderedAt() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateOrderedAt()
	})
}

// Exec executes the query.
func (u *OrderUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OrderCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OrderCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OrderUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
