// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/order"
	"github.com/Wei-Shaw/sub2api/ent/plan"
)

// PlanCreate is the builder for creating a Plan entity.
type PlanCreate struct {
	config
	mutation *PlanMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *PlanCreate) SetCreatedAt(v time.Time) *PlanCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PlanCreate) SetNillableCreatedAt(v *time.Time) *PlanCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PlanCreate) SetUpdatedAt(v time.Time) *PlanCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PlanCreate) SetNillableUpdatedAt(v *time.Time) *PlanCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *PlanCreate) SetDeletedAt(v time.Time) *PlanCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *PlanCreate) SetNillableDeletedAt(v *time.Time) *PlanCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *PlanCreate) SetName(v string) *PlanCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *PlanCreate) SetDescription(v string) *PlanCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *PlanCreate) SetNillableDescription(v *string) *PlanCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetPrice sets the "price" field.
func (_c *PlanCreate) SetPrice(v int) *PlanCreate {
	_c.mutation.SetPrice(v)
	return _c
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_c *PlanCreate) SetNillablePrice(v *int) *PlanCreate {
	if v != nil {
		_c.SetPrice(*v)
	}
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *PlanCreate) SetCurrency(v string) *PlanCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_c *PlanCreate) SetNillableCurrency(v *string) *PlanCreate {
	if v != nil {
		_c.SetCurrency(*v)
	}
	return _c
}

// SetValidityDays sets the "validity_days" field.
func (_c *PlanCreate) SetValidityDays(v int) *PlanCreate {
	_c.mutation.SetValidityDays(v)
	return _c
}

// SetNillableValidityDays sets the "validity_days" field if the given value is not nil.
func (_c *PlanCreate) SetNillableValidityDays(v *int) *PlanCreate {
	if v != nil {
		_c.SetValidityDays(*v)
	}
	return _c
}

// SetConcurrency sets the "concurrency" field.
func (_c *PlanCreate) SetConcurrency(v int) *PlanCreate {
	_c.mutation.SetConcurrency(v)
	return _c
}

// SetNillableConcurrency sets the "concurrency" field if the given value is not nil.
func (_c *PlanCreate) SetNillableConcurrency(v *int) *PlanCreate {
	if v != nil {
		_c.SetConcurrency(*v)
	}
	return _c
}

// SetFeatures sets the "features" field.
func (_c *PlanCreate) SetFeatures(v []string) *PlanCreate {
	_c.mutation.SetFeatures(v)
	return _c
}

// SetIcon sets the "icon" field.
func (_c *PlanCreate) SetIcon(v string) *PlanCreate {
	_c.mutation.SetIcon(v)
	return _c
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (_c *PlanCreate) SetNillableIcon(v *string) *PlanCreate {
	if v != nil {
		_c.SetIcon(*v)
	}
	return _c
}

// SetIsRecommended sets the "is_recommended" field.
func (_c *PlanCreate) SetIsRecommended(v bool) *PlanCreate {
	_c.mutation.SetIsRecommended(v)
	return _c
}

// SetNillableIsRecommended sets the "is_recommended" field if the given value is not nil.
func (_c *PlanCreate) SetNillableIsRecommended(v *bool) *PlanCreate {
	if v != nil {
		_c.SetIsRecommended(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *PlanCreate) SetStatus(v string) *PlanCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *PlanCreate) SetNillableStatus(v *string) *PlanCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *PlanCreate) SetSortOrder(v int) *PlanCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *PlanCreate) SetNillableSortOrder(v *int) *PlanCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// AddGroupIDs adds the "groups" edge to the Group entity by IDs.
func (_c *PlanCreate) AddGroupIDs(ids ...int64) *PlanCreate {
	_c.mutation.AddGroupIDs(ids...)
	return _c
}

// AddGroups adds the "groups" edges to the Group entity.
func (_c *PlanCreate) AddGroups(v ...*Group) *PlanCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddGroupIDs(ids...)
}

// AddOrderIDs adds the "orders" edge to the Order entity by IDs.
func (_c *PlanCreate) AddOrderIDs(ids ...int64) *PlanCreate {
	_c.mutation.AddOrderIDs(ids...)
	return _c
}

// AddOrders adds the "orders" edges to the Order entity.
func (_c *PlanCreate) AddOrders(v ...*Order) *PlanCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddOrderIDs(ids...)
}

// Mutation returns the PlanMutation object of the builder.
func (_c *PlanCreate) Mutation() *PlanMutation {
	return _c.mutation
}

// Save creates the Plan in the database.
func (_c *PlanCreate) Save(ctx context.Context) (*Plan, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PlanCreate) SaveX(ctx context.Context) *Plan {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PlanCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PlanCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PlanCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if plan.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized plan.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := plan.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if plan.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized plan.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := plan.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Price(); !ok {
		v := plan.DefaultPrice
		_c.mutation.SetPrice(v)
	}
	if _, ok := _c.mutation.Currency(); !ok {
		v := plan.DefaultCurrency
		_c.mutation.SetCurrency(v)
	}
	if _, ok := _c.mutation.ValidityDays(); !ok {
		v := plan.DefaultValidityDays
		_c.mutation.SetValidityDays(v)
	}
	if _, ok := _c.mutation.Concurrency(); !ok {
		v := plan.DefaultConcurrency
		_c.mutation.SetConcurrency(v)
	}
	if _, ok := _c.mutation.Icon(); !ok {
		v := plan.DefaultIcon
		_c.mutation.SetIcon(v)
	}
	if _, ok := _c.mutation.IsRecommended(); !ok {
		v := plan.DefaultIsRecommended
		_c.mutation.SetIsRecommended(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := plan.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := plan.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *PlanCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Plan.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Plan.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Plan.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := plan.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Plan.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Price(); !ok {
		return &ValidationError{Name: "price", err: errors.New(`ent: missing required field "Plan.price"`)}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "Plan.currency"`)}
	}
	if v, ok := _c.mutation.Currency(); ok {
		if err := plan.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "Plan.currency": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ValidityDays(); !ok {
		return &ValidationError{Name: "validity_days", err: errors.New(`ent: missing required field "Plan.validity_days"`)}
	}
	if _, ok := _c.mutation.Concurrency(); !ok {
		return &ValidationError{Name: "concurrency", err: errors.New(`ent: missing required field "Plan.concurrency"`)}
	}
	if _, ok := _c.mutation.Icon(); !ok {
		return &ValidationError{Name: "icon", err: errors.New(`ent: missing required field "Plan.icon"`)}
	}
	if v, ok := _c.mutation.Icon(); ok {
		if err := plan.IconValidator(v); err != nil {
			return &ValidationError{Name: "icon", err: fmt.Errorf(`ent: validator failed for field "Plan.icon": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsRecommended(); !ok {
		return &ValidationError{Name: "is_recommended", err: errors.New(`ent: missing required field "Plan.is_recommended"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Plan.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := plan.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Plan.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "Plan.sort_order"`)}
	}
	return nil
}

func (_c *PlanCreate) sqlSave(ctx context.Context) (*Plan, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PlanCreate) createSpec() (*Plan, *sqlgraph.CreateSpec) {
	var (
		_node = &Plan{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(plan.Table, sqlgraph.NewFieldSpec(plan.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(plan.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(plan.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(plan.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(plan.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(plan.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if value, ok := _c.mutation.Price(); ok {
		_spec.SetField(plan.FieldPrice, field.TypeInt, value)
		_node.Price = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(plan.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.ValidityDays(); ok {
		_spec.SetField(plan.FieldValidityDays, field.TypeInt, value)
		_node.ValidityDays = value
	}
	if value, ok := _c.mutation.Concurrency(); ok {
		_spec.SetField(plan.FieldConcurrency, field.TypeInt, value)
		_node.Concurrency = value
	}
	if value, ok := _c.mutation.Features(); ok {
		_spec.SetField(plan.FieldFeatures, field.TypeJSON, value)
		_node.Features = value
	}
	if value, ok := _c.mutation.Icon(); ok {
		_spec.SetField(plan.FieldIcon, field.TypeString, value)
		_node.Icon = value
	}
	if value, ok := _c.mutation.IsRecommended(); ok {
		_spec.SetField(plan.FieldIsRecommended, field.TypeBool, value)
		_node.IsRecommended = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(plan.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(plan.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if nodes := _c.mutation.GroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   plan.GroupsTable,
			Columns: plan.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.OrdersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plan.OrdersTable,
			Columns: []string{plan.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Plan.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PlanUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PlanCreate) OnConflict(opts ...sql.ConflictOption) *PlanUpsertOne {
	_c.conflict = opts
	return &PlanUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Plan.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PlanCreate) OnConflictColumns(columns ...string) *PlanUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PlanUpsertOne{
		create: _c,
	}
}

type (
	// PlanUpsertOne is the builder for "upsert"-ing
	//  one Plan node.
	PlanUpsertOne struct {
		create *PlanCreate
	}

	// PlanUpsert is the "OnConflict" setter.
	PlanUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *PlanUpsert) SetUpdatedAt(v time.Time) *PlanUpsert {
	u.Set(plan.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PlanUpsert) UpdateUpdatedAt() *PlanUpsert {
	u.SetExcluded(plan.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *PlanUpsert) SetDeletedAt(v time.Time) *PlanUpsert {
	u.Set(plan.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *PlanUpsert) UpdateDeletedAt() *PlanUpsert {
	u.SetExcluded(plan.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *PlanUpsert) ClearDeletedAt() *PlanUpsert {
	u.SetNull(plan.FieldDeletedAt)
	return u
}

// SetName sets the "name" field.
func (u *PlanUpsert) SetName(v string) *PlanUpsert {
	u.Set(plan.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *PlanUpsert) UpdateName() *PlanUpsert {
	u.SetExcluded(plan.FieldName)
	return u
}

// SetDescription sets the "description" field.
func (u *PlanUpsert) SetDescription(v string) *PlanUpsert {
	u.Set(plan.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *PlanUpsert) UpdateDescription() *PlanUpsert {
	u.SetExcluded(plan.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *PlanUpsert) ClearDescription() *PlanUpsert {
	u.SetNull(plan.FieldDescription)
	return u
}

// SetPrice sets the "price" field.
func (u *PlanUpsert) SetPrice(v int) *PlanUpsert {
	u.Set(plan.FieldPrice, v)
	return u
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *PlanUpsert) UpdatePrice() *PlanUpsert {
	u.SetExcluded(plan.FieldPrice)
	return u
}

// AddPrice adds v to the "price" field.
func (u *PlanUpsert) AddPrice(v int) *PlanUpsert {
	u.Add(plan.FieldPrice, v)
	return u
}

// SetCurrency sets the "currency" field.
func (u *PlanUpsert) SetCurrency(v string) *PlanUpsert {
	u.Set(plan.FieldCurrency, v)
	return u
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *PlanUpsert) UpdateCurrency() *PlanUpsert {
	u.SetExcluded(plan.FieldCurrency)
	return u
}

// SetValidityDays sets the "validity_days" field.
func (u *PlanUpsert) SetValidityDays(v int) *PlanUpsert {
	u.Set(plan.FieldValidityDays, v)
	return u
}

// UpdateValidityDays sets the "validity_days" field to the value that was provided on create.
func (u *PlanUpsert) UpdateValidityDays() *PlanUpsert {
	u.SetExcluded(plan.FieldValidityDays)
	return u
}

// AddValidityDays adds v to the "validity_days" field.
func (u *PlanUpsert) AddValidityDays(v int) *PlanUpsert {
	u.Add(plan.FieldValidityDays, v)
	return u
}

// SetConcurrency sets the "concurrency" field.
func (u *PlanUpsert) SetConcurrency(v int) *PlanUpsert {
	u.Set(plan.FieldConcurrency, v)
	return u
}

// UpdateConcurrency sets the "concurrency" field to the value that was provided on create.
func (u *PlanUpsert) UpdateConcurrency() *PlanUpsert {
	u.SetExcluded(plan.FieldConcurrency)
	return u
}

// AddConcurrency adds v to the "concurrency" field.
func (u *PlanUpsert) AddConcurrency(v int) *PlanUpsert {
	u.Add(plan.FieldConcurrency, v)
	return u
}

// SetFeatures sets the "features" field.
func (u *PlanUpsert) SetFeatures(v []string) *PlanUpsert {
	u.Set(plan.FieldFeatures, v)
	return u
}

// UpdateFeatures sets the "features" field to the value that was provided on create.
func (u *PlanUpsert) UpdateFeatures() *PlanUpsert {
	u.SetExcluded(plan.FieldFeatures)
	return u
}

// ClearFeatures clears the value of the "features" field.
func (u *PlanUpsert) ClearFeatures() *PlanUpsert {
	u.SetNull(plan.FieldFeatures)
	return u
}

// SetIcon sets the "icon" field.
func (u *PlanUpsert) SetIcon(v string) *PlanUpsert {
	u.Set(plan.FieldIcon, v)
	return u
}

// UpdateIcon sets the "icon" field to the value that was provided on create.
func (u *PlanUpsert) UpdateIcon() *PlanUpsert {
	u.SetExcluded(plan.FieldIcon)
	return u
}

// SetIsRecommended sets the "is_recommended" field.
func (u *PlanUpsert) SetIsRecommended(v bool) *PlanUpsert {
	u.Set(plan.FieldIsRecommended, v)
	return u
}

// UpdateIsRecommended sets the "is_recommended" field to the value that was provided on create.
func (u *PlanUpsert) UpdateIsRecommended() *PlanUpsert {
	u.SetExcluded(plan.FieldIsRecommended)
	return u
}

// SetStatus sets the "status" field.
func (u *PlanUpsert) SetStatus(v string) *PlanUpsert {
	u.Set(plan.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PlanUpsert) UpdateStatus() *PlanUpsert {
	u.SetExcluded(plan.FieldStatus)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *PlanUpsert) SetSortOrder(v int) *PlanUpsert {
	u.Set(plan.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *PlanUpsert) UpdateSortOrder() *PlanUpsert {
	u.SetExcluded(plan.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *PlanUpsert) AddSortOrder(v int) *PlanUpsert {
	u.Add(plan.FieldSortOrder, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Plan.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PlanUpsertOne) UpdateNewValues() *PlanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(plan.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Plan.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PlanUpsertOne) Ignore() *PlanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PlanUpsertOne) DoNothing() *PlanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PlanCreate.OnConflict
// documentation for more info.
func (u *PlanUpsertOne) Update(set func(*PlanUpsert)) *PlanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PlanUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PlanUpsertOne) SetUpdatedAt(v time.Time) *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PlanUpsertOne) UpdateUpdatedAt() *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *PlanUpsertOne) SetDeletedAt(v time.Time) *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *PlanUpsertOne) UpdateDeletedAt() *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *PlanUpsertOne) ClearDeletedAt() *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *PlanUpsertOne) SetName(v string) *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *PlanUpsertOne) UpdateName() *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *PlanUpsertOne) SetDescription(v string) *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *PlanUpsertOne) UpdateDescription() *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *PlanUpsertOne) ClearDescription() *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.ClearDescription()
	})
}

// SetPrice sets the "price" field.
func (u *PlanUpsertOne) SetPrice(v int) *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.SetPrice(v)
	})
}

// AddPrice adds v to the "price" field.
func (u *PlanUpsertOne) AddPrice(v int) *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.AddPrice(v)
	})
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *PlanUpsertOne) UpdatePrice() *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.UpdatePrice()
	})
}

// SetCurrency sets the "currency" field.
func (u *PlanUpsertOne) SetCurrency(v string) *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *PlanUpsertOne) UpdateCurrency() *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateCurrency()
	})
}

// SetValidityDays sets the "validity_days" field.
func (u *PlanUpsertOne) SetValidityDays(v int) *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.SetValidityDays(v)
	})
}

// AddValidityDays adds v to the "validity_days" field.
func (u *PlanUpsertOne) AddValidityDays(v int) *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.AddValidityDays(v)
	})
}

// UpdateValidityDays sets the "validity_days" field to the value that was provided on create.
func (u *PlanUpsertOne) UpdateValidityDays() *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateValidityDays()
	})
}

// SetConcurrency sets the "concurrency" field.
func (u *PlanUpsertOne) SetConcurrency(v int) *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.SetConcurrency(v)
	})
}

// AddConcurrency adds v to the "concurrency" field.
func (u *PlanUpsertOne) AddConcurrency(v int) *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.AddConcurrency(v)
	})
}

// UpdateConcurrency sets the "concurrency" field to the value that was provided on create.
func (u *PlanUpsertOne) UpdateConcurrency() *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateConcurrency()
	})
}

// SetFeatures sets the "features" field.
func (u *PlanUpsertOne) SetFeatures(v []string) *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.SetFeatures(v)
	})
}

// UpdateFeatures sets the "features" field to the value that was provided on create.
func (u *PlanUpsertOne) UpdateFeatures() *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateFeatures()
	})
}

// ClearFeatures clears the value of the "features" field.
func (u *PlanUpsertOne) ClearFeatures() *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.ClearFeatures()
	})
}

// SetIcon sets the "icon" field.
func (u *PlanUpsertOne) SetIcon(v string) *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.SetIcon(v)
	})
}

// UpdateIcon sets the "icon" field to the value that was provided on create.
func (u *PlanUpsertOne) UpdateIcon() *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateIcon()
	})
}

// SetIsRecommended sets the "is_recommended" field.
func (u *PlanUpsertOne) SetIsRecommended(v bool) *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.SetIsRecommended(v)
	})
}

// UpdateIsRecommended sets the "is_recommended" field to the value that was provided on create.
func (u *PlanUpsertOne) UpdateIsRecommended() *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateIsRecommended()
	})
}

// SetStatus sets the "status" field.
func (u *PlanUpsertOne) SetStatus(v string) *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PlanUpsertOne) UpdateStatus() *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateStatus()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *PlanUpsertOne) SetSortOrder(v int) *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *PlanUpsertOne) AddSortOrder(v int) *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *PlanUpsertOne) UpdateSortOrder() *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateSortOrder()
	})
}

// Exec executes the query.
func (u *PlanUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PlanCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PlanUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PlanUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PlanUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PlanCreateBulk is the builder for creating many Plan entities in bulk.
type PlanCreateBulk struct {
	config
	err      error
	builders []*PlanCreate
	conflict []sql.ConflictOption
}

// Save creates the Plan entities in the database.
func (_c *PlanCreateBulk) Save(ctx context.Context) ([]*Plan, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Plan, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PlanMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PlanCreateBulk) SaveX(ctx context.Context) []*Plan {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PlanCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PlanCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Plan.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PlanUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PlanCreateBulk) OnConflict(opts ...sql.ConflictOption) *PlanUpsertBulk {
	_c.conflict = opts
	return &PlanUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Plan.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PlanCreateBulk) OnConflictColumns(columns ...string) *PlanUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PlanUpsertBulk{
		create: _c,
	}
}

// PlanUpsertBulk is the builder for "upsert"-ing
// a bulk of Plan nodes.
type PlanUpsertBulk struct {
	create *PlanCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Plan.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PlanUpsertBulk) UpdateNewValues() *PlanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(plan.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Plan.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PlanUpsertBulk) Ignore() *PlanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PlanUpsertBulk) DoNothing() *PlanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PlanCreateBulk.OnConflict
// documentation for more info.
func (u *PlanUpsertBulk) Update(set func(*PlanUpsert)) *PlanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PlanUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PlanUpsertBulk) SetUpdatedAt(v time.Time) *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PlanUpsertBulk) UpdateUpdatedAt() *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *PlanUpsertBulk) SetDeletedAt(v time.Time) *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *PlanUpsertBulk) UpdateDeletedAt() *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *PlanUpsertBulk) ClearDeletedAt() *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *PlanUpsertBulk) SetName(v string) *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *PlanUpsertBulk) UpdateName() *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *PlanUpsertBulk) SetDescription(v string) *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *PlanUpsertBulk) UpdateDescription() *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *PlanUpsertBulk) ClearDescription() *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.ClearDescription()
	})
}

// SetPrice sets the "price" field.
func (u *PlanUpsertBulk) SetPrice(v int) *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.SetPrice(v)
	})
}

// AddPrice adds v to the "price" field.
func (u *PlanUpsertBulk) AddPrice(v int) *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.AddPrice(v)
	})
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *PlanUpsertBulk) UpdatePrice() *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.UpdatePrice()
	})
}

// SetCurrency sets the "currency" field.
func (u *PlanUpsertBulk) SetCurrency(v string) *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *PlanUpsertBulk) UpdateCurrency() *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateCurrency()
	})
}

// SetValidityDays sets the "validity_days" field.
func (u *PlanUpsertBulk) SetValidityDays(v int) *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.SetValidityDays(v)
	})
}

// AddValidityDays adds v to the "validity_days" field.
func (u *PlanUpsertBulk) AddValidityDays(v int) *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.AddValidityDays(v)
	})
}

// UpdateValidityDays sets the "validity_days" field to the value that was provided on create.
func (u *PlanUpsertBulk) UpdateValidityDays() *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateValidityDays()
	})
}

// SetConcurrency sets the "concurrency" field.
func (u *PlanUpsertBulk) SetConcurrency(v int) *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.SetConcurrency(v)
	})
}

// AddConcurrency adds v to the "concurrency" field.
func (u *PlanUpsertBulk) AddConcurrency(v int) *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.AddConcurrency(v)
	})
}

// UpdateConcurrency sets the "concurrency" field to the value that was provided on create.
func (u *PlanUpsertBulk) UpdateConcurrency() *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateConcurrency()
	})
}

// SetFeatures sets the "features" field.
func (u *PlanUpsertBulk) SetFeatures(v []string) *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.SetFeatures(v)
	})
}

// UpdateFeatures sets the "features" field to the value that was provided on create.
func (u *PlanUpsertBulk) UpdateFeatures() *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateFeatures()
	})
}

// ClearFeatures clears the value of the "features" field.
func (u *PlanUpsertBulk) ClearFeatures() *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.ClearFeatures()
	})
}

// SetIcon sets the "icon" field.
func (u *PlanUpsertBulk) SetIcon(v string) *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.SetIcon(v)
	})
}

// UpdateIcon sets the "icon" field to the value that was provided on create.
func (u *PlanUpsertBulk) UpdateIcon() *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateIcon()
	})
}

// SetIsRecommended sets the "is_recommended" field.
func (u *PlanUpsertBulk) SetIsRecommended(v bool) *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.SetIsRecommended(v)
	})
}

// UpdateIsRecommended sets the "is_recommended" field to the value that was provided on create.
func (u *PlanUpsertBulk) UpdateIsRecommended() *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateIsRecommended()
	})
}

// SetStatus sets the "status" field.
func (u *PlanUpsertBulk) SetStatus(v string) *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PlanUpsertBulk) UpdateStatus() *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateStatus()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *PlanUpsertBulk) SetSortOrder(v int) *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *PlanUpsertBulk) AddSortOrder(v int) *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *PlanUpsertBulk) UpdateSortOrder() *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateSortOrder()
	})
}

// Exec executes the query.
func (u *PlanUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PlanCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PlanCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PlanUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
